[tool.bumpversion]
current_version = "9.22.1"
commit = true
message = "Update version {current_version} -> {new_version}"

[[tool.bumpversion.files]]
filename = "README.md"
search = "{current_version}"
replace = "{new_version}"
